# Urbano, Antonio Gabriel L.
# 2ECE-A

In [1]:
import pandas as pd

In [2]:
cars = pd.read_csv('cars.csv')

### A. POSITIONAL AND LABEL-BASED SLICING

In [4]:
print("Shape of cars DataFrame:", cars.shape)
print("List of Column Names:", list(cars.columns))

cars_6_to_10 = cars.iloc[5:10]

cars_6_to_10.loc[:, ['Model', 'mpg', 'cyl', 'hp', 'gear']]

Shape of cars DataFrame: (32, 12)
List of Column Names: ['Model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

        Model   mpg  cyl   hp  gear
5     Valiant  18.1    6  105     3
6  Duster 360  14.3    8  245     3
7   Merc 240D  24.4    4   62     4
8    Merc 230  22.8    4   95     4
9    Merc 280  19.2    6  123     4

### B. MODEL LOOKUP

In [5]:
toyota = cars.loc[cars['Model'] == 'Toyota Corolla']
display(toyota)

pontiac = cars.loc[cars['Model'] == 'Pontiac Firebird', ['Model', 'mpg', 'hp', 'wt']]
display(pontiac)

             Model   mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
19  Toyota Corolla  33.9    4  71.1  65  4.22  1.835  19.9   1   1     4     1

               Model   mpg   hp     wt
24  Pontiac Firebird  19.2  175  3.845

### C. MULTI-MODEL SUBSETTING

In [6]:
target_models = ['Datsun 710', 'Lotus Europa', 'Ferrari Dino']
target_columns = ['Model', 'mpg', 'cyl', 'hp', 'gear']

selected_cars = cars.loc[cars['Model'].isin(target_models), target_columns ]

display(selected_cars)
print("Shape of selected_cars:", selected_cars.shape)

           Model   mpg  cyl   hp  gear
2     Datsun 710  22.8    4   93     4
27  Lotus Europa  30.4    4  113     5
29  Ferrari Dino  19.7    6  175     5

Shape of selected_cars: (3, 5)